version: '3.8'

services:
  mysql:
    image: mysql:8.0.36
    container_name: email-auth-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: demo-email-auth
      MYSQL_USER: demo-auth-email
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:4.1.0-management
    container_name: email-auth-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  mysql-data: {}
