server:
  port: 8081

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8082
          predicates:
            - Path=/api/auth/**
        - id: email
          uri: http://localhost:8083
          predicates:
            - Path=/api/email/**

      default-filters:
        - AddRequestHeader: X-Gateway, Gateway-Service

  main:
    web-application-type: reactive
