server:
  port: 8082

spring:
  application:
    name: auth

  datasource:
    url: jdbc:mysql://localhost:3306/demo-email-auth
    username: demo-auth-email
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  liquibase:
    enabled: false

rabbitmq:
  email:
    exchange: email.exchange
    queue: email.queue
    routing-key: email.routing-key