server:
  port: 8083

spring:
  application:
    name: email

  datasource:
    url: jdbc:mysql://localhost:3306/demo-email-auth
    username: demo-auth-email
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.gmail.com
    port: 587
    username: adidasdn1510.bao@gmail.com
    password: gvxs drqz hudh ihpu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

rabbitmq:
  email:
    exchange: email.exchange
    queue: email.queue
    routing-key: email.routing-key